# cspell:ignore cibuildwheel, CIBW, gfortran, manylinux, akima

name: Build Push and Publish

on:
  push:
    # tags:
    #   - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['cp38', 'cp39', 'cp310', 'cp311', 'cp312', 'cp313']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build and Test Wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix-python-version }}-manylinux_x86_64
          CIBW_ENVIRONMENT: >
            F90=gfortran
            F77=gfortran
          CIBW_TEST_COMMAND: >
            python {project}/test/test_akima.py

      - name: Archive Wheels
        run: |
          tar -czf wheels-${{ matrix.python-version }}.tar.gz wheelhouse /

      - name: Upload Wheel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}
          path: wheels-${{ matrix.python-version }}.tar.gz
