# cspell:ignore cibuildwheel, CIBW, gfortran, manylinux, akima

name: Build Push and Publish

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['cp38', 'cp39', 'cp310', 'cp311', 'cp312', 'cp313']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build and Test Wheels
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.python-version }}-manylinux_x86_64
          CIBW_ENVIRONMENT: >
            F90=gfortran
            F77=gfortran
          CIBW_TEST_COMMAND: >
            python {project}/test/test_akima.py

      - name: Archive Wheels
        run: |
          tar -czf wheels-${{ matrix.python-version }}.tar.gz -C wheelhouse .

      - name: Upload Wheel Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}
          path: wheels-${{ matrix.python-version }}.tar.gz
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Wheel Artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Extract all wheels
        run: |
          mkdir -p all_wheels
          find dist -name '*.tar.gz' -exec tar -xzf {} -C all_wheels \;

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: ${{ PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
          packages_dir: all_wheels
